apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app: image-automation-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: image-automation-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: squaremo/image-automation-controller
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
