apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: imageupdateautomation-sample
spec:
  checkout:
    gitRepositoryRef:
      name: app-repo
    branch: main
  interval: 5m
  # update strategy is left to default to "Setters"
  commit:
    authorName: Fluxbot
    authorEmail: fluxbot@example.com
