name: build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Restore go cache
      uses: actions/cache@v1
      with:
        # the ff is mounted into the container as ~/go/pkg/mod
        path: /home/runner/work/_temp/_github_home/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set up kubebuilder
      uses: fluxcd/pkg/actions/kubebuilder@main
    - name: Run tests
      uses: ./.github/actions/run-tests
      env:
        GOPATH: /github/home/go
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
